import user from "@/assets/Logo/avatar.png";


export const reviews = [
    // 5-star reviews (8)
    {
        id: 1,
        name: "রবিউল হাসান",
        role: "Founder",
        product: "Butters' LEGENDARY Product",
        stars: 5,
        date: "Feb 16, 2022",
        text: "Butter will forever change how you approach online or remote workshop collaboration - from the facilitator or the participant; this unique tool will add flavour, fun and discipline for more engaging digital workshops.",
        avatar: user.src,
    },
    {
        id: 2,
        name: "জারিন তাসনিম",
        role: "CEO",
        product: "Visionary SaaS",
        stars: 5,
        date: "Mar 5, 2022",
        text: "Absolutely love the platform! It has transformed our workflow and increased our team productivity by 40%.",
        avatar: user.src,
    },
    {
        id: 3,
        name: "সাবরিনা ইসলাম",
        role: "Product Manager",
        product: "Product Pro",
        stars: 5,
        date: "Apr 12, 2022",
        text: "The best product in its category. Our team uses it daily and couldn't be happier with the results.",
        avatar: user.src,
    },
    {
        id: 4,
        name: "মাহমুদুল হক",
        role: "CTO",
        product: "Tech Suite",
        stars: 5,
        date: "May 8, 2022",
        text: "Exceptional quality and service. The support team is responsive and knowledgeable.",
        avatar: user.src,
    },
    {
        id: 5,
        name: "ইশরাত জahan",
        role: "Marketing Director",
        product: "Marketing Pro",
        stars: 5,
        date: "Jun 10, 2022",
        text: "This has revolutionized how we approach our marketing campaigns. Worth every penny!",
        avatar: user.src,
    },
    {
        id: 6,
        name: "রিফাত আহমেদ",
        role: "Developer",
        product: "Dev Tools",
        stars: 5,
        date: "Jul 15, 2022",
        text: "As a developer, I appreciate the clean API and thorough documentation. Makes integration a breeze.",
        avatar: user.src,
    },
    {
        id: 7,
        name: "তানজিনা রহমান",
        role: "Design Lead",
        product: "Design Suite",
        stars: 5,
        date: "Aug 20, 2022",
        text: "The design tools are intuitive and powerful. Our team has created stunning visuals in half the time.",
        avatar: user.src,
    },
    {
        id: 8,
        name: "সজীব করিম",
        role: "Sales Executive",
        product: "Sales Accelerator",
        stars: 5,
        date: "Sep 3, 2022",
        text: "Our conversion rates have improved dramatically since implementing this solution. Highly recommended!",
        avatar: user.src,
    },

    // 4-star reviews (8)
    {
        id: 9,
        name: "আরাফাত রহমান",
        role: "Developer",
        product: "Dev Tools Pro",
        stars: 4,
        date: "Apr 12, 2022",
        text: "Very useful, but could improve on speed. Overall a great product with minor performance issues.",
        avatar: user.src,
    },
    {
        id: 10,
        name: "মারিয়া খাতুন",
        role: "Designer",
        product: "Creative Kit",
        stars: 4,
        date: "May 8, 2022",
        text: "Loved the design tools, super intuitive. Would give 5 stars if there were more template options.",
        avatar: user.src,
    },
    {
        id: 11,
        name: "তামিম ইকবাল",
        role: "Analyst",
        product: "Data Insights",
        stars: 4,
        date: "Jun 5, 2022",
        text: "Powerful analytics features, though the learning curve is a bit steep for new users.",
        avatar: user.src,
    },
    {
        id: 12,
        name: "অনন্যা সরকার",
        role: "HR Manager",
        product: "HR Suite",
        stars: 4,
        date: "Jul 18, 2022",
        text: "Great for our HR processes, but the mobile app needs some improvements to match the web version.",
        avatar: user.src,
    },
    {
        id: 13,
        name: "রায়han চৌধুরী",
        role: "Consultant",
        product: "Business Pro",
        stars: 4,
        date: "Aug 22, 2022",
        text: "Excellent features overall, though I wish the pricing was more transparent from the start.",
        avatar: user.src,
    },
    {
        id: 14,
        name: "সাফা yesmin",
        role: "Educator",
        product: "Edu Platform",
        stars: 4,
        date: "Sep 10, 2022",
        text: "My students love it! Would be perfect with better integration with other educational tools.",
        avatar: user.src,
    },
    {
        id: 15,
        name: "ওয়াসিক ফার্সি",
        role: "Engineer",
        product: "Engineering Tools",
        stars: 4,
        date: "Oct 5, 2022",
        text: "Reliable and robust, though some features feel a bit outdated compared to competitors.",
        avatar: user.src,
    },
    {
        id: 16,
        name: "গ্রেস লায়লা",
        role: "Content Creator",
        product: "Content Studio",
        stars: 4,
        date: "Nov 15, 2022",
        text: "Makes content creation much easier, though I occasionally experience small bugs.",
        avatar: user.src,
    },

    // 3-star reviews (8)
    {
        id: 17,
        name: "জাহিদ হাসান",
        role: "Manager",
        product: "Business Suite",
        stars: 3,
        date: "Jun 10, 2022",
        text: "Good features but needs better support. Sometimes takes days to get responses to critical issues.",
        avatar: user.src,
    },
    {
        id: 18,
        name: "এমা পারভীন",
        role: "Freelancer",
        product: "Freelance Hub",
        stars: 3,
        date: "Jul 15, 2022",
        text: "Works well but has a learning curve. Not as intuitive as I expected for the price point.",
        avatar: user.src,
    },
    {
        id: 19,
        name: "দানিয়াল রহমান",
        role: "Photographer",
        product: "Photo Editor",
        stars: 3,
        date: "Aug 5, 2022",
        text: "Decent editing tools, but lacks some advanced features that competitors offer at this price.",
        avatar: user.src,
    },
    {
        id: 20,
        name: "মেগনা সুলতানা",
        role: "Writer",
        product: "Writing Assistant",
        stars: 3,
        date: "Sep 12, 2022",
        text: "Helpful for basic writing, but the AI suggestions often miss the mark for professional content.",
        avatar: user.src,
    },
    {
        id: 21,
        name: "কেভিন তালুকদার",
        role: "Accountant",
        product: "Finance Pro",
        stars: 3,
        date: "Oct 8, 2022",
        text: "Does the job, but the interface feels clunky compared to other financial software I've used.",
        avatar: user.src,
    },
    {
        id: 22,
        name: "রেখা মল্লিক",
        role: "Social Media Manager",
        product: "Social Suite",
        stars: 3,
        date: "Nov 20, 2022",
        text: "Average performance. Scheduling works fine but analytics could be more detailed.",
        avatar: user.src,
    },
    {
        id: 23,
        name: "ব্রায়ান কাদের",
        role: "Small Business Owner",
        product: "Business Starter",
        stars: 3,
        date: "Dec 5, 2022",
        text: "Good for basic needs, but outgrew it quickly. Better suited for very small operations.",
        avatar: user.src,
    },
    {
        id: 24,
        name: "লারা দাস",
        role: "Project Manager",
        product: "Task Master",
        stars: 3,
        date: "Jan 10, 2023",
        text: "Functional but not exceptional. There are better project management tools available.",
        avatar: user.src,
    },

    // 2-star reviews (8)
    {
        id: 25,
        name: "দানিয়েল সরকার",
        role: "Consultant",
        product: "Pro Consult",
        stars: 2,
        date: "Aug 20, 2022",
        text: "Some features didn't work as expected. Support was unhelpful when I reached out about issues.",
        avatar: user.src,
    },
    {
        id: 26,
        name: "পত্রী লায়লা",
        role: "Teacher",
        product: "Classroom Pro",
        stars: 2,
        date: "Sep 5, 2022",
        text: "Frustrating to use. Many promised features either don't work well or are missing entirely.",
        avatar: user.src,
    },
    {
        id: 27,
        name: "জর্জ মিয়া",
        role: "Retail Manager",
        product: "Retail Solutions",
        stars: 2,
        date: "Oct 15, 2022",
        text: "Barely functional for our needs. Had to supplement with other tools to get basic functionality.",
        avatar: user.src,
    },
    {
        id: 28,
        name: "হ্যানা বেগম",
        role: "Event Planner",
        product: "Event Pro",
        stars: 2,
        date: "Nov 8, 2022",
        text: "Constant bugs make this nearly unusable for professional event planning. Very disappointed.",
        avatar: user.src,
    },
    {
        id: 29,
        name: "নাথান ওয়াদুদ",
        role: "IT Specialist",
        product: "IT Toolkit",
        stars: 2,
        date: "Dec 12, 2022",
        text: "Security vulnerabilities found during our audit. Can't recommend until these are fixed.",
        avatar: user.src,
    },
    {
        id: 30,
        name: "ভিক্টোরিয়া সুলতানা",
        role: "Blogger",
        product: "Blog Platform",
        stars: 2,
        date: "Jan 5, 2023",
        text: "Limited customization options and frequent downtime. Moving to a different platform soon.",
        avatar: user.src,
    },
    {
        id: 31,
        name: "এরিক জাহাঙ্গীর",
        role: "Fitness Trainer",
        product: "Fitness Pro",
        stars: 2,
        date: "Feb 10, 2023",
        text: "App crashes frequently during client sessions. Unreliable for professional use.",
        avatar: user.src,
    },
    {
        id: 32,
        name: "ডায়ানা করিম",
        role: "Restaurateur",
        product: "Restaurant Manager",
        stars: 2,
        date: "Mar 15, 2023",
        text: "Missing critical features for inventory management. Had to implement manual workarounds.",
        avatar: user.src,
    },

    // 1-star reviews (8)
    {
        id: 33,
        name: "অলিভিয়া বেগম",
        role: "Student",
        product: "Learn Fast",
        stars: 1,
        date: "Sep 3, 2022",
        text: "Didn't meet my expectations at all. Content was outdated and platform was buggy.",
        avatar: user.src,
    },
    {
        id: 34,
        name: "মার্ক টি. হোসেন",
        role: "Entrepreneur",
        product: "Startup Kit",
        stars: 1,
        date: "Oct 10, 2022",
        text: "Complete waste of money. None of the advertised features worked properly.",
        avatar: user.src,
    },
    {
        id: 35,
        name: "জেনিফার লতিফ",
        role: "Graphic Designer",
        product: "Design Pro",
        stars: 1,
        date: "Nov 5, 2022",
        text: "Terrible user experience. Crashes constantly and corrupts files. Avoid this product!",
        avatar: user.src,
    },
    {
        id: 36,
        name: "স্টিভেন পি. রহমান",
        role: "Architect",
        product: "CAD Tools",
        stars: 1,
        date: "Dec 8, 2022",
        text: "Unusable for professional work. Lost hours of work due to crashes and poor autosave.",
        avatar: user.src,
    },
    {
        id: 37,
        name: "আমান্ডা রহমান",
        role: "Video Editor",
        product: "Video Suite",
        stars: 1,
        date: "Jan 12, 2023",
        text: "Renders low quality output despite high settings. Support refused to issue a refund.",
        avatar: user.src,
    },
    {
        id: 38,
        name: "পল হক",
        role: "Musician",
        product: "Music Studio",
        stars: 1,
        date: "Feb 15, 2023",
        text: "Latency makes recording impossible. Basic features that should work don't function at all.",
        avatar: user.src,
    },
    {
        id: 39,
        name: "নিকোল ওয়াহেদ",
        role: "Therapist",
        product: "Therapy Tools",
        stars: 1,
        date: "Mar 10, 2023",
        text: "Security concerns with client data. Immediately discontinued use after discovering vulnerabilities.",
        avatar: user.src,
    },
    {
        id: 40,
        name: "জেসন মল্লিক",
        role: "Developer",
        product: "Code Assistant",
        stars: 1,
        date: "Apr 5, 2023",
        text: "Generated code was often incorrect or insecure. Dangerous to use in production environments.",
        avatar: user.src,
    },
];